export enum NotificationType {
  BOOKING_CONFIRMED = "BOOKING_CONFIRMED",
  BOOKING_RESCHEDULED = "BOOKING_RESCHEDULED",
  BOOKING_CANCELLED = "BOOKING_CANCELLED",
  BOOKING_COMPLETED = "BOOKING_COMPLETED",
  KYC_REQUEST = "KYC_REQUEST",
}